### ISSUE TITLE
[An error occurred in the loading package versions (package:MyPackage)] Unexpected token ﻿ in JSON at position 0

### ISSUE THREAD

**Issue by GrooveXT** [aliasadidev/vscode-npm-gui#15]
Hey,

when I try to "Load Package Versions" I get this error:
[An error occurred in the loading package versions (package:MyPackage)] Unexpected token ﻿ in JSON at position 0

MyPackage lives on a gitlab nuget registry which is defined in a nuget.config. 

Any idea what the problem could be?

thx

**Comment by adrianzlobinski** [comment]
Same problem on my private nuget repository

**Comment by cspwizard** [comment]
This plugin doesn't respect nuget.config, and it's unclear how to set up private nuget repo via plugin config.

**Comment by blushingpenguin** [comment]
The error message could be better, but this plugin simply doesn't work with private repos. I started figuring out how to add support for this but ran out of time -- it's unfortunately not as easy as I would have hoped (the protocol doesn't seem to be explicitly documented -- it is wrapped up in https://github.com/NuGet/NuGet.Client)

**Comment by aliasadidev** [comment]
I'm sorry for the late response.

To use Gitlab's private repo, you have to do two steps:
1. Config your NuGet.Config ([gitlab docs](https://docs.gitlab.com/ee/user/packages/nuget_repository/))

`file path ~/.nuget/NuGet/NuGet.Config`
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageSources>
		<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
		<add key="gitlab" value="http://localhost/api/v4/projects/2/packages/nuget/index.json" />
	</packageSources>
	<packageSourceCredentials>
		<gitlab>
                  <add key="Username" value="<gitlab_username or deploy_token_username>" />
                  <add key="ClearTextPassword" value="<gitlab_personal_access_token or deploy_token>" />
		</gitlab>
	</packageSourceCredentials>
</configuration>
```

2. Config the settings.json in VSCode

```json
	"nugetpackagemanagergui.nuget.searchPackage.urls": [
		"https://azuresearch-usnc.nuget.org/query",
		"http://localhost/api/v4/projects/2/packages/nuget/query"
	],
	"nugetpackagemanagergui.nuget.packageVersionsUrls": [
		"https://api.nuget.org/v3-flatcontainer/{{packageName}}/index.json",
		"http://localhost/api/v4/projects/2/packages/nuget/download/{{packageName}}/index.json"
	],

```

**Comment by aliasadidev** [comment]
I've tested it in Gitlab 14.0.2-ee

**Comment by aliasadidev** [comment]
> Hey,
> 
> when I try to "Load Package Versions" I get this error:
> [An error occurred in the loading package versions (package:MyPackage)] Unexpected token ﻿ in JSON at position 0
> 
> MyPackage lives on a gitlab nuget registry which is defined in a nuget.config.
> 
> Any idea what the problem could be?
> 
> thx

Open the VSCode Developer Tools to see the error details

**Comment by cspwizard** [comment]
> I've tested it in Gitlab 14.0.2-ee

great! Thanks!

Do you have snippets for nexus?

**Comment by aliasadidev** [comment]
> > I've tested it in Gitlab 14.0.2-ee
> 
> great! Thanks!
> 
> Do you have snippets for nexus?

Go to Repository>Repositories>Select nuget-hosted 

![image](https://user-images.githubusercontent.com/6399165/124299573-94b68b80-db2b-11eb-8b1f-03099353bb81.png)

append "/index.json" to the end of URL and then open it in the browser to see the result.

*http://localhost:8081/repository/nuget-hosted/index.json*
`compare it with nuget https://api.nuget.org/v3/index.json`

```js
	"nugetpackagemanagergui.nuget.searchPackage.urls": [
		"http://localhost:8081/repository/nuget-hosted/v3/query/0" // Nexus Repository
		// "https://azuresearch-usnc.nuget.org/query", // Nuget Repository
		// "http://localhost/api/v4/projects/2/packages/nuget/query" // GitLab Repository
	],
	"nugetpackagemanagergui.nuget.packageVersionsUrls": [
		"http://localhost:8081/repository/nuget-hosted/v3/content/{{packageName}}/index.json" // Nexus Repository
		// "https://api.nuget.org/v3-flatcontainer/{{packageName}}/index.json", // Nuget Repository
		// "http://localhost/api/v4/projects/2/packages/nuget/download/{{packageName}}/index.json" // GitLab Repository
	],
```

**Comment by cspwizard** [comment]
Thanks! unfortunately didn't worked with nexus (I think due to nexus bug) will investigate it later. 
Also find out the reason for the "Unexpected token ﻿ in JSON at position 0" somehow the response from the nuget server is in xml format with content 
`<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:ff69c6a6-a01e-002e-4d84-71b092000000
Time:2021-07-05T09:57:21.2919830Z</Message></Error>` and it's not handled

**Comment by aliasadidev** [comment]
> Thanks! unfortunately didn't worked with nexus (I think due to nexus bug) will investigate it later.
> Also find out the reason for the "Unexpected token ﻿ in JSON at position 0" somehow the response from the nuget server is in xml format with content
> `<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist. RequestId:ff69c6a6-a01e-002e-4d84-71b092000000 Time:2021-07-05T09:57:21.2919830Z</Message></Error>` and it's not handled

I've installed Nexus Repository Manager (NXRM) 3 on Docker, and It worked well. The result should be the standard JSON (like 
 https://api.nuget.org/v3/index.json)

**Comment by cspwizard** [comment]
yep, for someone it works. However I've the situation similar to https://issues.sonatype.org/browse/NEXUS-28224 and nexus throws 502.
