### ISSUE TITLE
Feature Request - click on package name to open nuget.org page

### ISSUE THREAD

**Issue by AlexPiksel** [aliasadidev/vscode-npm-gui#16]
**Feature Request**
Update the GUI so the package name is a hyperlink to the package page on nuget.org.

**Scenario**
I recently used the extension when updating a large .NET Core 2.2 project to .NET Core 3.1 LTS.

Many of the latest versions of the packages we use in our project require .NET 5, which we are not yet ready to move to. As such, when there is a major version update to a package, it's necessary to check the dependencies on nuget.org to see whether we are able to use it with .NET Core 3.1. Currently, this involves C&Ping the package name from the GUI and pasting it into the search box on nuget.org, which is a bit fiddly when you are using a lot of packages. The ability to simply click a hyperlink to open the nuget page would save a lot of time.

Anyway, thank you for the wonderful extension! It has already saved me hours of work, and it's lightning fast.

**Comment by aliasadidev** [comment]
It sounds good.
I'll add it in the next release.

**Comment by aliasadidev** [comment]
It's done in version 2
