### ISSUE TITLE
The  packageName must be lower case?

### ISSUE THREAD

**Issue by aihui109** [aliasadidev/vscode-npm-gui#22]
if “https://api.nuget.org/v3-flatcontainer/Newtonsoft.Json/index.json” , show httpcode 404，Have to “https://nuget.cdn.azure.cn/v3-flatcontainer/newtonsoft.json/index.json”

**Comment by aliasadidev** [comment]
> if “[https://api.nuget.org/v3-flatcontainer/Newtonsoft.Json/index.json”](https://api.nuget.org/v3-flatcontainer/Newtonsoft.Json/index.json%E2%80%9D) , show httpcode 404，Have to “[https://nuget.cdn.azure.cn/v3-flatcontainer/newtonsoft.json/index.json”](https://nuget.cdn.azure.cn/v3-flatcontainer/newtonsoft.json/index.json%E2%80%9D)

[Newtonsoft.Json](https://api.nuget.org/v3-flatcontainer/Newtonsoft.Json/index.json)  works fine for me, the second address wasn't reachable

> The packageName must be lower case?
https://api.nuget.org/v3-flatcontainer/Newtonsoft.Json/index.json
https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
both are same

**Comment by aihui109** [comment]
Thanks！，This is my screenshot:
![1](https://user-images.githubusercontent.com/37268088/127792383-5bafd903-6d4b-4b39-be7b-4cf34c663f10.png)
![2](https://user-images.githubusercontent.com/37268088/127792389-dde083db-ec16-4d7d-9d06-028faa791141.png)

**Comment by aihui109** [comment]
Here are some instructions: "The package ID, lowercased"
 [https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource](url)
