### ISSUE TITLE
Can not see list of .NET projects due to one python project in the list

### ISSUE THREAD

**Issue by VishalJadav** [aliasadidev/vscode-npm-gui#25]
I have 5-6 .NET Projects and one python under one root folder.  I can see project list in GUI only when I remove python project. Is there any setting to exclude specific project?

**Comment by aliasadidev** [comment]
This extension ignores `.git` and `node_modules` folders.
https://github.com/aliasadidev/vscode-npm-gui/blob/d4a63a571e4e090b954e5c61482abf5b8daaeb24/src/services/project.service.ts#L24

To see the error detail, follow the below steps:
VSCode -> Menu -> Help -> Toggle Developer Tools > Console Tab
