### ISSUE TITLE
Select an item list empty

### ISSUE THREAD

**Issue by professorwolfe** [aliasadidev/vscode-npm-gui#29]
Trying to add a package (Bootstrap). It asks me to choose a project from the select an item drop down. Nothing is in the list. I have aa workspace open. How do I get something in the drop down.
![image](https://user-images.githubusercontent.com/61847994/135639778-26e611c0-016e-4a22-85ba-77f65b661b87.png)

**Comment by aliasadidev** [comment]
This extension only works with .net core/.net 5+ projects, I can't see any .csproj file in your workspace.

**Comment by professorwolfe** [comment]
Thanks for clarifying I see that now.
