### ISSUE TITLE
[bug] Format of csproj files is modified when updating packages

### ISSUE THREAD

**Issue by LordMike** [aliasadidev/vscode-npm-gui#34]
I'm kind of excited because we finally have a fast gui for updates .. :)

But I'm saddened to find out that the format of the csproj files are rewritten entirely, when changes occur. So this means my (intentional) empty lines disappear, indentation is changed to some other style and so on.

So in the end, the resulting change is a lot more than just version numbers, which sucks :/

An alternative way is to use regexes to modify the file in place, or if the msbuild system is used to edit the csproj files using the API, it is possible to trick it to keep the format as it was. I'm not sure how this project does it.

**Comment by aliasadidev** [comment]
Thank you! :) 
I find a way to avoid change indentation.

**Comment by aliasadidev** [comment]
I fixed the issue, only unit tests remain( too many states should be tested)

**Comment by aliasadidev** [comment]
@LordMike 
It's fixed on version 2.0.4
