### ISSUE TITLE
Packages from Azure DevOps Artifacts Shows in Reverse Order

### ISSUE THREAD

**Issue by tilicon** [aliasadidev/vscode-npm-gui#36]
When loading package versions the oldest version shows as newest.

![Screenshot 2022-03-22 at 18 29 08](https://user-images.githubusercontent.com/7198461/159540412-6cd22f3f-20bb-40e0-9f96-a4f22cec33a6.png)

 
This is not an issue when loading packages from NuGet, only our Azure DevOps Artifacts.

Here's a snippet from the feed which looks fine to me.
`
{
  "@type": "Package",
  "id": "#redacted#",
  "version": "1.0.0.18456",
  "versions": [
    {
      "@id": "#redacted#",
      "downloads": 0,
      "version": "1.0.0.18456"
    },
    {
      "@id": "#redacted#",
      "downloads": 0,
      "version": "1.0.0.18454"
    }
  ]
}
`

**Comment by aliasadidev** [comment]
Thanks for reporting.
I think I need to write a strong function to handle unordered list( I think only Azure has this behavior)
I will fix it in the next release.
```json
{
    "@type": "Package",
    "id": "#redacted#",
    "version": "1.0.0.18456",
    "versions": [
        {
            "@id": "#redacted#",
            "downloads": 0,
            "version": "1.0.0.18456"
        },
        {
            "@id": "#redacted#",
            "downloads": 0,
            "version": "1.0.0.18454"
        }
    ]
}
```

**Comment by aliasadidev** [comment]
The problem is fixed. I will prepare a PR for it.

**Comment by aliasadidev** [comment]
you can test it in version 2.0.2

**Comment by tilicon** [comment]
> 

Works like a charm! Thank you for an awesome product.
