### ISSUE TITLE
Activating "NuGet package manager GUI" yields empty screen

### ISSUE THREAD

**Issue by yuvalrakavy** [aliasadidev/vscode-npm-gui#51]
It used to work, and now all I get is an empty black screen...

**Comment by h0lg** [comment]
Same. This happened for me after upgrading to VS Code 1.73.0

**Comment by luizen** [comment]
Same here :(

**Comment by crackfan** [comment]
![image](https://user-images.githubusercontent.com/2922399/200471884-f6cdefa2-b4b0-45e3-b130-8f4d09acc33c.png)

**Comment by aliasadidev** [comment]
fixed with #52

**Comment by h0lg** [comment]
> fixed with #52
please update to 2.0.5

**Confirmed**. **Thanks** for the quick fix and keep up the good work!
